# https://taskfile.dev

version: "3"

vars:
  DB: ./storage.db
  BINARY: foodtracker
  VERSION: dev
  BUILDTIME:
    sh: date -u +%Y-%m-%dT%H:%M:%SZ
  COMMIT:
    sh: git rev-parse HEAD

tasks:
  migrate:
    cmds:
      - goose -dir ./migrations sqlite3 {{.DB}} up
  build:
    desc: Build binary
    cmds:
      - |
        go build -ldflags "-X 'main.Version={{.VERSION}}' \
                           -X 'main.BuildTime={{.BUILDTIME}}' \
                           -X 'main.Commit={{.COMMIT}}' \
                           -s -w" \
                 -o bin/{{.BINARY}} cmd/app/main.go
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - go.mod
      - go.sum
    generates:
      - bin/{{.BINARY}}
  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin
